services:
    standalone-chrome:
      shm_size: 2g
      image: selenium/standalone-chrome:124.0-chromedriver-124.0-20250606
      container_name: standalone-chrome
      depends_on:
        - vpn
      network_mode: "service:vpn"
    vpn:
      image: thrnz/docker-wireguard-pia
      container_name: docker-wireguard-pia
      ports:
        - 4444:4444
        - 7900:7900
      volumes:
        - pia:/pia
      cap_add:
        - NET_ADMIN
      environment:
        - LOC=us_california
        - USER=${pia_username}
        - PASS=${pia_password}
        - LOCAL_NETWORK=192.168.2.0/24
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.default.disable_ipv6=1
        - net.ipv6.conf.all.disable_ipv6=1
        - net.ipv6.conf.lo.disable_ipv6=1

volumes:
  pia: