services:
    standalone-chrome:
      shm_size: 2g
      image: selenium/standalone-chrome:124.0-chromedriver-124.0-20250606
      container_name: standalone-chrome
      depends_on:
        - vpn
      network_mode: "service:vpn"
    vpn:
      image: thrnz/docker-wireguard-pia
      container_name: docker-wireguard-pia
      ports:
        - 4444:4444
        - 7900:7900
      volumes:
        #Auth token is stored here
        - pia:/pia
        # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
        # - pia-shared:/pia-shared
      cap_add:
        - NET_ADMIN
        # SYS_MODULE might not be needed with a 5.6+ kernel?
        #- SYS_MODULE
      # If the kernel module isn't available, mounting the tun device may be necessary for userspace implementations
      #devices:
        #- /dev/net/tun:/dev/net/tun
      environment:
        # The following env vars are required:
        - LOC=us_california
        - USER=${pia_username}
        - PASS=${pia_password}
        #The rest are optional:
        - LOCAL_NETWORK=192.168.2.0/24
        #- RECONNECT=1
        #- KEEPALIVE=25
        #- VPNDNS=8.8.8.8,8.8.4.4
        #- PORT_FORWARDING=1
      sysctls:
        # The wg-quick script tries to set this when setting up routing, however this requires running the container
        # with the --privileged flag set. Setting it here instead if needed means the container can be run with lower
        # privileges. This only needs setting if strict reverse path filtering (rp_filter=1) is used.
        - net.ipv4.conf.all.src_valid_mark=1
        # May as well disable ipv6. Should be blocked anyway.
        - net.ipv6.conf.default.disable_ipv6=1
        - net.ipv6.conf.all.disable_ipv6=1
        - net.ipv6.conf.lo.disable_ipv6=1

volumes:
  pia: